name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}
description: ${project.description}
soft-depend: [Vault]

commands:
  menu:
    description: The base for all menu actions
    usage: /menu [create|edit|delete|list|open|script|reload|grab|copy] [parameters...]
    aliases: [m]
    permissions: cyom.commands.menu
  
permissions:
  cyom.commands.menu.*:
    description: Allows use of all menu commands
    default: op
    children:
      cyom.commands.menu.create: true
      cyom.commands.menu.copy: true
      cyom.commands.menu.edit: true
      cyom.commands.menu.delete: true
      cyom.commands.menu.list: true
      cyom.commands.menu.open: true
      cyom.commands.menu.script: true
      cyom.commands.menu.reload: true
      cyom.commands.menu.grab: true
  cyom.commands.menu.create:
    description: Allows creating of new menus
    default: op
  cyom.commands.menu.copy:
    description: Allows copying of existing menus
    default: op
  cyom.commands.menu.edit:
    description: Allows editing of existing menus
    default: op
  cyom.commands.menu.delete:
    description: Allows removing of existing menus
    default: op
  cyom.commands.menu.list:
    description: Allows listing of all menus
    default: op
  cyom.commands.menu.open:
    description: Allows opening of menus for other players
    default: op
  cyom.commands.menu.script:
    description: Allows scripting of menu items
    default: op
  cyom.commands.menu.reload:
    description: Allows reloading of menus from disk
    default: op
  cyom.commands.menu.grab:
    description: Allows grabbing copies of items from a menu
    default: op
